image: rvancea/maven-chrome-jdk8:latest

build:
    stage: build
    script:
       - echo "Compiling the code..."
       - echo "Compile compelte."

test:
    stage: test
    script:
        - mvn clean install